#!/bin/bash
pkill -9 -f "quiccla" 2>/dev/null
( cd unibo-run 2>/dev/null && unset UNIBO_BP && unibo-bp-admin stop ) \
	>/dev/null 2>&1
pkill -9 -f "unibo-bp" 2>/dev/null
ionstop >/dev/null 2>&1
killm >/dev/null 2>&1
rm -f ion.log testfile* payload_u2i payload_i2u server.pem server.key
rm -f config/interop_runtime.bprc config/interop_runtime.ipnrc
rm -rf unibo-run
exit 0
