#!/bin/bash
pkill -9 -x tcpv4cla 2>/dev/null
ionstop >/dev/null 2>&1
killm >/dev/null 2>&1
rm -f ion.log testfile1 sendfile counter.out
rm -f config/loopback_runtime.bprc config/loopback_runtime.ipnrc
exit 0
