#!/bin/bash
pkill -9 -f "quiccli" 2>/dev/null
pkill -9 -f "quicclo" 2>/dev/null
ionstop >/dev/null 2>&1
killm >/dev/null 2>&1
rm -f ion.log testfile1 sendfile server.pem server.key
rm -f config/loopback_runtime.bprc config/loopback_runtime.ipnrc
exit 0
